import {
  ArrowUpDown,
  Banknote,
  Baby,
  Briefcase,
  Car,
  ClipboardCheck,
  Dog,
  DoorOpen,
  Droplets,
  Dumbbell,
  Eye,
  FileText,
  Flame,
  Home,
  KeyRound,
  MapPin,
  ShieldCheck,
  Sofa,
  Sun,
  Trees,
  Utensils,
  Warehouse,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP: Array<[string, LucideIcon]> = [
  ["lift", ArrowUpDown],
  ["balcony", DoorOpen],
  ["kitchen", Utensils],
  ["borehole", Droplets],
  ["water", Droplets],
  ["security", ShieldCheck],
  ["cctv", ShieldCheck],
  ["fenc", ShieldCheck],
  ["manned", ShieldCheck],
  ["intercom", ShieldCheck],
  ["escrow", ShieldCheck],
  ["parking", Car],
  ["carport", Car],
  ["gym", Dumbbell],
  ["club", Warehouse],
  ["solar", Sun],
  ["natural light", Sun],
  ["view", Eye],
  ["glazing", Eye],
  ["skyline", Eye],
  ["generator", Zap],
  ["power", Zap],
  ["internet", Zap],
  ["fibre", Zap],
  ["wifi", Zap],
  ["garden", Trees],
  ["tree", Trees],
  ["plot", Trees],
  ["land", Trees],
  ["beacon", MapPin],
  ["title", FileText],
  ["freehold", FileText],
  ["tenure", FileText],
  ["supervision", ClipboardCheck],
  ["qs", ClipboardCheck],
  ["payment", Banknote],
  ["financing", Banknote],
  ["yield", Banknote],
  ["playground", Baby],
  ["children", Baby],
  ["pet", Dog],
  ["staff", Home],
  ["dsq", Home],
  ["quarters", Home],
  ["fireplace", Flame],
  ["air conditioning", Wind],
  ["meeting", Briefcase],
  ["business", Briefcase],
  ["server", Briefcase],
  ["furnished", Sofa],
  ["mezzanine", KeyRound],
  ["dressing", KeyRound],
  ["office", Briefcase],
];

export function amenityIcon(label: string): LucideIcon {
  const lower = label.toLowerCase();
  for (const [keyword, icon] of MAP) {
    if (lower.includes(keyword)) return icon;
  }
  return KeyRound;
}
