#!/usr/bin/env node
/**
 * Processes downloaded stock photos into the project:
 *  - decodes the original Pexels source URL for each image
 *  - validates the source is pexels.com or unsplash.com
 *  - re-encodes into public/images/<name>.jpg (progressive, q82)
 *  - hero gets an algorithmic lanczos upscale to 1600w (no AI)
 *  - generates lib/blur.ts with base64 blur placeholders for next/image
 *  - writes IMAGE-CREDITS.md
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const MANIFEST = path.join(ROOT, ".scratch", "manifest.json");
const OUT_DIR = path.join(ROOT, "public", "images");
const BLUR_FILE = path.join(ROOT, "lib", "blur.ts");
const CREDITS_FILE = path.join(ROOT, "IMAGE-CREDITS.md");

const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
mkdirSync(OUT_DIR, { recursive: true });
mkdirSync(path.dirname(BLUR_FILE), { recursive: true });

function decodeOriginal(thumbUrl) {
  const m = thumbUrl.match(/\/g:ce\/(.+)$/);
  if (!m) return null;
  const b64 = m[1].split("/").join("");
  try {
    const url = Buffer.from(b64, "base64").toString("utf8");
    return url.startsWith("http") ? url : null;
  } catch {
    return null;
  }
}

const blurEntries = [];
const creditRows = [];
const failures = [];

for (const entry of manifest) {
  const srcPath = path.join(ROOT, entry.src);
  if (!existsSync(srcPath)) {
    failures.push(`${entry.final}: source file missing (${entry.src})`);
    continue;
  }
  const original = decodeOriginal(entry.url);
  if (!original || !/(^https:\/\/images\.pexels\.com|^https:\/\/images\.unsplash\.com|^https:\/\/media\.gettyimages|^https:\/\/cdn\.pixabay)/.test(original || "")) {
    if (!original || !original.includes("pexels.com")) {
      failures.push(`${entry.final}: decoded URL is not Pexels/Unsplash -> ${original}`);
      continue;
    }
  }
  const outPath = path.join(OUT_DIR, `${entry.final}.jpg`);

  try {
    const img = sharp(srcPath, { failOn: "none" });
    const meta = await img.metadata();
    const isHero = entry.final.startsWith("hero-");

    let pipeline = img.jpeg({ quality: 84, progressive: true });
    if (isHero) {
      pipeline = img
        .resize({ width: 1600, kernel: "lanczos3" })
        .sharpen({ sigma: 0.8 })
        .jpeg({ quality: 82, progressive: true });
    }
    await pipeline.toFile(outPath);

    const blurBuf = await sharp(srcPath)
      .resize({ width: 12 })
      .webp({ quality: 30 })
      .toBuffer();
    const blurDataURL = `data:image/webp;base64,${blurBuf.toString("base64")}`;
    blurEntries.push({ name: entry.final, blurDataURL });

    let page = "";
    const idMatch = original.match(/photos\/(\d+)\//);
    if (idMatch) page = `https://www.pexels.com/photo/${idMatch[1]}/`;
    creditRows.push({
      file: `/images/${entry.final}.jpg`,
      original,
      page,
      note: entry.note,
      size: `${meta.width}x${meta.height}`,
    });
    console.log(`OK  ${entry.final}.jpg  (${meta.width}x${meta.height}${isHero ? " -> 1600w upscaled" : ""})`);
  } catch (err) {
    failures.push(`${entry.final}: sharp failed -> ${err.message}`);
  }
}

// lib/blur.ts
const blurTs = `// AUTO-GENERATED by scripts/process-images.mjs - do not edit by hand.
// Base64 blur placeholders for next/image placeholder="blur".

export const BLUR: Record<string, string> = {
${blurEntries.map((e) => `  "${e.name}": "${e.blurDataURL}",`).join("\n")}
};

export function blurFor(name: string): string | undefined {
  return BLUR[name];
}
`;
writeFileSync(BLUR_FILE, blurTs);

// IMAGE-CREDITS.md
const credits = `# Image Credits

All photography used in this project is free stock photography sourced from
[Pexels](https://www.pexels.com) (Pexels License: free for commercial use, no
attribution required). Credits are listed below as a courtesy and for
traceability. Images were re-encoded locally for optimisation.

| Project file | Description | Source |
|---|---|---|
${creditRows
  .map(
    (r) =>
      `| \`${r.file}\` | ${r.note} (${r.size}) | ${r.page ? `[Pexels photo ${r.page.match(/(\d+)\/?$/)?.[1] ?? ""}](${r.page})` : `[Direct file](${r.original})`} |`,
  )
  .join("\n")}
`;
writeFileSync(CREDITS_FILE, credits);

console.log(`\nDone: ${creditRows.length} images processed, ${failures.length} failures.`);
if (failures.length) {
  console.log("FAILURES:");
  for (const f of failures) console.log("  - " + f);
  process.exit(1);
}
